### ISSUE TITLE
Dynamically set the date of the next event

### ISSUE THREAD

**Issue by TheAmazingPT** [Moinworld/wtm-website#19]
For the counter on the front page its required to write a date for the next event hard into the source code.
It would be more convenient to use the meetup.com API and request the next event date dynamically.

What are you thinking about it? How shall we tackle it and shall we maybe make it topic in one of the next events?

**Comment by ilithya** [comment]
@TheAmazingPT Yes, we will do it and show it at the next WTM JS Workshop.

Btw. Thank you so much for those hotfixes. I just merged both from the scroll to top button (svg) and the encoding for the closing menu button. 

As long as Anja deploys that at our new hosting, it'll be live. We switched to Firebase now.

I'll be in touch soon, once we set up a date for the next JS Workshop.

**Comment by marymar** [comment]
@ilithya: I was curios about knowing if there is a way accessing the meetup api without using oAuth and I found a way. I pushed my example into the feature branch feature/#19:
https://github.com/Moinworld/wtm-website/tree/feature/%2319

It is not the best way doing so, because it might cost security risks, but it is maybe the first we could go for?!

**Comment by TheAmazingPT** [comment]
@marymar could you please post a pull request, so we can have a nice overview of your changes? Implementation discussions can happen there =)

**Comment by ilithya** [comment]
@marymar Thanks Mary.
@TheAmazingPT Steffi and I took a look at it yesterday and I just pushed this on our master branch after testing it in our develop branch.

An interesting bug we still had was that the counter was not counting right. Always adding 1 extra day, even when fetching the right current and next event date from the Meetup API.

After long debugging, and going a bit crazy together with Steffi, I found out it was about using getUTCDate() instead of getDate() in the var days. Did you guys know about this? 

Btw. I also went ahead and fetched the event name from the API, so the counter not only displays the amount of time resting for the next event, but also which event is coming up.

I'll go ahead and close that pull request and this issue.
You can comment on the counter error here on issue #37.
